server:
  port: 80
spring:
  application:
    name: cloud-consumer-order80
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hanchun123
  #P94 需要的配置
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1   #采样率值介于0-1之间,1标识全部采集

eureka:
  client:
    service-url:
    #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #,http://eureka7003.com:7003/eureka/
    register-with-eureka: true  #客户端注册进eureka服务列表内
    #是否从EurekaServer抓取已有的注册信息,单机无所谓,集群必须设置为true配合ribbon使用负载均衡
    fetch-registry: true

  instance:
    instance-id: cloud-consumer-order80  #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

